# Generated by Django 4.1.4 on 2023-01-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_moviedata_typ"),
    ]

    operations = [
        migrations.AddField(
            model_name="moviedata",
            name="image",
            field=models.ImageField(
                default="Images/None/noimg.jpg", upload_to="Images/"
            ),
        ),
    ]
